name: Update Chrome Extension
on:
  push:
    branches:
      - master
env:
  SHA: ${{ github.sha }}
jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |-
          npx pnpm install
          npx pnpm build:chrome
          # we archive the dist folder and include SHA commit as the last step
          cd dist/chrome
          zip -r chrome-extension-$SHA.zip ./*
          mv chrome-extension-$SHA.zip ../../
          cd -

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.sha }}.zip
  # api usage reference:
  # * <https://developer.chrome.com/docs/webstore/using_webstore_api/>
  # * <https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md>
  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16.10"

      - name: Download bundle artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Upload step
        run: npx chrome-webstore-upload-cli@2 upload --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CI_GOOGLE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}